I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/a_script_base.rpy", line 36, in script
    return
  File "game/a_script_base.rpy", line 36, in script
    return
ScriptError: could not find label '(u'C:\\Users\\ntyoo\\gitarea\\ProjectExist/game/wtf_iorpy_magic.rpy', 1411710165, 3)'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/a_script_base.rpy", line 36, in script
    return
  File "C:\Users\ntyoo\Dropbox\Public Script\run_me_please\renpy\ast.py", line 1286, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "game/a_script_base.rpy", line 36, in script
    return
  File "C:\Users\ntyoo\Dropbox\Public Script\run_me_please\renpy\script.py", line 549, in lookup
    raise ScriptError("could not find label '%s'." % str(label))
ScriptError: could not find label '(u'C:\\Users\\ntyoo\\gitarea\\ProjectExist/game/wtf_iorpy_magic.rpy', 1411710165, 3)'.

Windows-post2008Server-6.2.9200
Ren'Py 6.17.7.521
Project Exist v0.2.5_(1031)
